import{a as y,i as n,S as h}from"./assets/vendor-c493984e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const f=t=>`
  <li class="gallery-card"><a class="gallery-link" href="${t.largeImageURL}">
    <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}"/>
</a><div class ="card-data">  <ul class="data-list"><li class="image-data"><p class="image-data-text">Views</p><p class="image-data-text">${t.views}</p></li>
  <li class="image-data"><p class="image-data-text">Likes</p><p class="image-data-text">${t.likes}</p></li>
  <li class="image-data"><p class="image-data-text">Comments</p><p class="image-data-text">${t.comments}</p></li>
  <li class="image-data"><p class="image-data-text">Downloads</p><p class="image-data-text">${t.downloads}</p></li>
  </ul></div></li>
  `;y.defaults.baseURL="https://pixabay.com/";const L=(t,a)=>{const r={params:{key:"45485539-1e2d85f159a7ac8a3c50871fa",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}};return y.get("api/",r)},d=document.querySelector(".search-form"),p=document.querySelector(".gallery"),l=document.querySelector(".loader"),i=document.querySelector(".js-load-more");let u="",m=1,w=0,c=0;const v=async t=>{if(t.preventDefault(),m=1,c=0,u=d.elements.user_query.value.trim(),i.classList.contains("is-hidden")||i.classList.add("is-hidden"),u===""){n.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}l.classList.add("is-open");const a=await L(u,m);if(a.data.total===0){l.classList.remove("is-open"),d.reset(),n.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),p.innerHTML="";return}const r=a.data.hits.map(e=>f(e)).join("");if(d.reset(),l.classList.remove("is-open"),p.innerHTML=r,new h(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250}).refresh(),w=p.querySelector("li").getBoundingClientRect().height,c=document.querySelectorAll(".gallery-card"),a.data.totalHits===c.length){n.show({message:"That's all we could find on your request",color:"yellow",position:"topRight"});return}i.classList.remove("is-hidden")},b=async t=>{m+=1,l.classList.add("is-open");const a=await L(u,m),r=a.data.hits.map(o=>f(o)).join("");p.insertAdjacentHTML("beforeend",r),new h(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250}).refresh(),l.classList.remove("is-open"),scrollBy({top:w*2,behavior:"smooth"}),c=document.querySelectorAll(".gallery-card"),a.data.totalHits===c.length&&(i.classList.add("is-hidden"),n.show({message:"We're sorry, but you've reached the end of search results.",color:"yellow",position:"topRight"}))};d.addEventListener("submit",v);i.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
